### ISSUE TITLE
I hope there will be a function to reset sleep time by shaking it

### ISSUE THREAD

**Issue by lzren8** [GrakovNe/lissen-android#74]

**Comment by GrakovNe** [comment]
after a long research i cannot state at least the one app which has this feature. Could you point me an example please?

**Comment by Musrha** [comment]
Audiobookshelf official app has this feature (Settings - Sleep timer settings - Disable shake to reset)

**Comment by GrakovNe** [comment]
Thank you for your suggestion! After reviewing how this feature works in the official Audiobookshelf app, I’ve decided not to implement it in Lissen. It doesn’t align with Google’s guidelines or the principles of clear and transparent functionality. For example, resetting a timer just because the device was shaken—such as when being moved from one pocket to another—can lead to confusion and unintended behavior.

Additionally, I should mention that I have no plans to replicate features from the official app. The whole reason Lissen exists is that I wasn’t satisfied with the official app’s design and functionality. That’s why I’m focused on creating something different, with a better user experience. Still, I appreciate your feedback and am always open to hearing more ideas for improvement!

**Comment by wax-m** [comment]
Hey, i would like to draw back attention on this, as i feel it is important when listening to audiobooks when going to sleep for example.
I always have a sleeptimer on, and if i haven't fallen asleep as the sound starts to fade out i shake my phone (without having to press any buttons or turning it on) and playback continues.


Smart Audiobookplayer also has this feature, and it leads to me never turning the sleeptimer off at all

**Comment by belzebub40k** [comment]
+1

I'd really like to see this feature. It is the only thing that's keeping me from switching to Lissen. I mainly use audio books to fall asleep and not having an easy option to reset the sleep timer without fiddling with the app itself makes me stick with the official app.

**Comment by basings** [comment]
> I'd really like to see this feature. It is the only thing that's keeping me from switching to Lissen

+1

**Comment by jupue2707** [comment]
+1
